name: Deploy

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest # 使用最新的 ubuntu 系统

    steps:
      - uses: actions/checkout@v1 # 将代码拷贝到虚机中
      - name: Use Node.js
        uses: actions/setup-node@master
        with:
          node-version: '12.x'

      - name: Use cached Node modules # 使用缓存
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-
      
      - name: install # 安装 yarn 包
        run: yarn install --frozen-lockfile

      - name: yarn list # 输出 yarn 包
        run: yarn list --depth=0

      - name: build # 构建
        run: yarn run github

      - name: deploy # 发布到 gh-pages 分支
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USERNAME: moreant
          USEREMAIL: 552191481@qq.com
          REPOSITORY: yeek-outlook-api
          PUSH_BANCHE: gh-pages
          PUSH_MESSAGE: DeployGitHubPages
        run: |
          cd dist
          git init
          git config user.name "$USERNAME"
          git config user.email "$USEREMAIL"
          git remote add origin https://"$ACCESS_TOKEN"@github.com/"$USERNAME"/"$REPOSITORY".git
          git checkout -b "$PUSH_BANCHE"
          git add -A
          git commit -m ""$PUSH_MESSAGE""
          git push origin "$PUSH_BANCHE" --force
